void AllocArrays ();
void Init_F ();
void CBD_Step ();
void SetParams ();
void SetupJob ();
void SingleStep ();
void PrintSummary ();
void ReadInput ();
void writeProps();
void feneForce ();
void InitCoordsRand ();
void computeForcesHarmonic ();
void pairForceHarmonicLongRange(VecR& r1, VecR& r2, VecR& f1, VecR& f2, real& rho1, real& rho2, real k, real& fn1, real& fn2);
void PrintElapsedTime(chrono::steady_clock::time_point start);
void writePropsHeader();
real virialPres();
void cellDivision();
void pairForceContactHarmonic(VecR& r1, VecR& r2, VecR& f1, VecR& f2, real& rho1, real& rho2, real& fn1, real& fn2);
void cellDeath();
